substitutions:
  node_name: Gree AC # Use a unique name.
  node_id: Gree_ac    # Use a unique id.
  friendly_node_name: "Gree AC"
  deviceid: gree
  devicename: FlurOG

#esphome:
#  name: sinclair_asc18
#  platform: ESP8266
#  board: d1_mini

esphome:
#  name: sinclair_asc18
  name: "sinclair_asc18"
  friendly_name: "Gree AC"

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0 # disable LOG output on UART as UART is used for Gree AC unit
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret gree_key

ota:
  - platform: esphome
    password: !secret gree_otapw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gree Fallback Hotspot"
    password:  !secret appw

uart:
  id: asc18_uart
  tx_pin: 1      # GPIO1 (TX0) # ESP8266
  rx_pin: 3      # GPIO3 (RX0) # ESP8266
  baud_rate: 9600
  parity: NONE
  stop_bits: 1

time:
  - platform: sntp

# Custom-Component einbinden
external_components:
  - source: github://jipijajay/esphome_sinclair_asc18
    components: [sinclair_asc18]

climate:
  - platform: sinclair_asc18
    name:  ${devicename}
    uart_id: asc18_uart



